name: Keep Render App Alive (Simple Fetch)

on:
  schedule:
    - cron: "*/5 * * * *"   # κάθε 5'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Warm up app (HTTP GET with retries)
        run: |
          for i in {1..3}; do
            CODE=$(curl -sS -o /dev/null -w "%{http_code}" -A "Mozilla/5.0 GitHubAction KeepAlive" -L https://smart-load-scheduler.onrender.com)
            echo "Attempt $i: HTTP $CODE"
            if [ "$CODE" -ge 200 ] && [ "$CODE" -lt 400 ]; then
              echo "Ping successful"
              exit 0
            fi
            sleep 15
          done
          echo "All attempts failed"
          exit 1
